## This functions extracts member information from a csv file generated by the RECON registration
## google forms.

read.registration <- function(title = "Registrations"){
    if(!require("googlesheets")) {
        stop("googlesheets is required")
    }

    tib <- gs_read(gs_title(title))
    tib <- as.data.frame(tib)

    ## Processing of the tibble: we need to ensure lower case for the column names, and to sort
    ## the entries as follows:
    ## 1st: Jombart
    ## rest: alphabetically after the last name

    names(tib) <- tolower(names(tib))
    lastnames <- tolower(tib[, 3])
    rownames(tib) <- lastnames

    id.tj <- grep("jombart", lastnames)
    if (length(id.tj > 0)) {
        order <- c("jombart", sort(setdiff(lastnames, "jombart")))
    } else {
        order <- order(lastnames)
    }

    tib <- tib[order, ]

    ## The output will be the 'people-list:' item from the header of the .md file. We make a
    ## character vector, each item being a separate line in the output. The function 'read.one' will
    ## read one record and shape it into the relevant characters.

    out <- "people-list:"

    read.one <- function(x){

        ## name
        out <- paste("  - name:", x[2], x[3], sep=" ")

        ## image
        out <- c(out, tolower(paste0("    img: /img/people/",
                                     gsub(" ", "-", x[2]),
                                     "_",
                                     gsub(" ", "-",  x[3]),
                                     ".jpg")))
        ## description
        out <- c(out, paste(paste0("    desc: ", x[6]), x[7], x[8], collapse="", sep=", "))

        ## website
        if (!is.na(x$website)) {
            out <- c(out, paste0("    website: ", x$website))
        }

        ## github
        if (!is.na(x$github)) {
            out <- c(out, paste0("    github: ", x$github))
        }

        ## twitter
        if (!is.na(x$twitter)) {
            out <- c(out, paste0("    twitter: ", x$twitter))
        }

        return(out)
    }

    ## generate output - one item per row
    out <- c(out, unlist(lapply(seq_len(nrow(tib)), function(i) read.one(tib[i, ]))))
    out <- gsub("[.],", ",", out)
    out <- gsub(" NA,", "", out)

    cat("\n\n\n *** Copy-paste the following into people.md's header ***\n", out, "\n\n", sep="\n")
    return(invisible(out))

}
